---
# ---------------------------
# Kalliope default settings
# Use YAML syntax
# ---------------------------

# ---------------------------
# Trigger
# ---------------------------
# This is the trigger that will catch your magic work to wake up Kalliope
default_trigger: "snowboy"

# Trigger engine configuration
# Available engine are:
# - snowboy
triggers:
  - snowboy:
      pmdl_file: "trigger/kalliope-DE-samples.pmdl"


# ---------------------------
# Speech to text
# ---------------------------

# This is the STT that will be used by default
default_speech_to_text: "google"

# Spreech to Text engines configuration
# Available engine are:
# - google (via SpeechRecognition)
# -
speech_to_text:
  - google:
      language: "de-DE"

# ---------------------------
# Text to speech
# ---------------------------
# This is the default TTS that will be used by Kalliope to talk.
default_text_to_speech: "pico2wave"
# where we store generated audio files from TTS engine to reuse them
cache_path: "/tmp/kalliope_tts_cache"

# Text to Spreech engines configuration
# Available engine are:
# - pico2wave
# - voxygen
text_to_speech:
  - pico2wave:
      language: "de-DE"
      cache: True
  - voxygen:
      voice: "Jenny"
      cache: True
  - acapela:
      language: "sonid15"
      voice: "Manon"
      cache: True
  - googletts:
      language: "de"
      cache: True
  - voicerss:
      language: "de-DE"
      cache: True


# ---------------------------
# Wake up answers
# ---------------------------
# When Kalliope detect the hotword/trigger, he will select randomly a phrase in the following list
# to notify the user that he's listening for orders
random_wake_up_answers:
  - "ja bitte?"
  - "Ich höre?"
  - "Ich höre auf Dich?"
  - "Ja?"
  - "Was kann ich für Dich tun?"
  - "Wie kann ich Dir helfen?"

# You can play a sound when Kalliope detect the hotword/trigger instead of saying something from
# the `random_wake_up_answers`. To active the 'random_wake_up_sounds' you must comment out the 'random_wake_up_answers'
# The file must be .wav or .mp3 format.
random_wake_up_sounds:
  - "trigger/dong.wav"
  # - "/my/personal/full/path/my_file.mp3"

# ---------------------------
# On ready notification
# ---------------------------
# This section is used to notify the user when Kalliope is waiting for a trigger detection by playing a sound or speak a sentence out loud

# This parameter define if you play the on ready answer:
# - always: every time Kalliope is ready to be awaken
# - never: never play a sound or sentences when kalliope is ready
# - once: at the first start of Kalliope
play_on_ready_notification: "never"

# The on ready notification can be a sentence. Place here a sentence or a list of sentence. If you set a list, one sentence will be picked up randomly
on_ready_answers:
  - "waiting for order"

# You can play a sound instead of a sentence.
# Remove the `on_ready_answers` parameters by commenting it out and use this one instead.
# Place here the path of the sound file. Files must be .wav or .mp3 format.
on_ready_sounds:
#  - "sounds/ding.wav"
  - "sounds/dong.wav"

# ---------------------------
# Rest API
# ---------------------------
rest_api:
  active: True
  port: 5000
  password_protected: True
  login: admin
  password: secret

# ---------------------------
# Default Synapse
# ---------------------------
# Specify an optional default synapse response in case your order is not found.
default_synapse: "default-synapse"

# ---------------------------
# resource directory path
# ---------------------------
resource_directory:
  neuron: "resources/neurons"
  stt: "resources/stt"
  tts: "resources/tts"
